version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - N8N_PORT=5678
      - WEBHOOK_TUNNEL_URL=http://localhost:5678
      - N8N_SECURE_COOKIE=false  #Required for HTTP 
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ./ollama-data:/root/.ollama
      - ./script:/script
    restart: always
    entrypoint: ["/bin/sh", "-c", "/script/init.bash"]

  python-app:
    build:
      context: ./python-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: always

volumes:
  n8n_data:
  ollama:
    